/**
 * Embed system prompt markdown into a TypeScript module so
 * `bun build --compile` single-file binaries (Homebrew/Scoop) include them.
 *
 * Bun's virtual FS (`/$bunfs/root/`) only contains files the bundler sees.
 * Runtime `readFileSync` of sibling `.md` files fails there with ENOENT.
 * Generated output: src/prompts/embedded.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const promptsDir = join(root, "src", "prompts");
const files = ["system.ask.md", "system.agent.md"];

const entries = files.map((name) => {
  const body = readFileSync(join(promptsDir, name), "utf8");
  return `  ${JSON.stringify(name)}: ${JSON.stringify(body)},`;
});

const out = `/* AUTO-GENERATED by scripts/embed-prompts.mjs — do not edit by hand.
 * Source of truth: system.ask.md / system.agent.md
 * Re-run: node scripts/embed-prompts.mjs
 */
export const EMBEDDED_PROMPTS: Readonly<Record<string, string>> = {
${entries.join("\n")}
};
`;

const outPath = join(promptsDir, "embedded.ts");

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(outPath, "utf8");
  } catch {
    console.error(`Missing ${outPath}; run: node scripts/embed-prompts.mjs`);
    process.exit(1);
  }
  if (current !== out) {
    console.error(
      `Embedded prompts are stale versus the markdown sources.\n` +
        `Run: node scripts/embed-prompts.mjs, then commit ${outPath}.`,
    );
    process.exit(1);
  }
  console.log(`Embedded prompts match their sources (${files.length} prompts)`);
  process.exit(0);
}

mkdirSync(promptsDir, { recursive: true });
writeFileSync(outPath, out, "utf8");
console.log(`Wrote ${outPath} (${files.length} prompts)`);
