/**
 * Embed system prompt markdown into a TypeScript module so
 * `bun build --compile` single-file binaries (Homebrew/Scoop) include them.
 *
 * Bun's virtual FS (`/$bunfs/root/`) only contains files the bundler sees.
 * Runtime `readFileSync` of sibling `.md` files fails there with ENOENT.
 * Generated output: src/prompts/embedded.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const promptsDir = join(root, "src", "prompts");
const files = ["system.ask.md", "system.agent.md"];

const entries = files.map((name) => {
  const body = readFileSync(join(promptsDir, name), "utf8");
  return `  ${JSON.stringify(name)}: ${JSON.stringify(body)},`;
});

const out = `/* AUTO-GENERATED by scripts/embed-prompts.mjs — do not edit by hand.
 * Source of truth: system.ask.md / system.agent.md
 * Re-run: node scripts/embed-prompts.mjs
 */
export const EMBEDDED_PROMPTS: Readonly<Record<string, string>> = {
${entries.join("\n")}
};
`;

mkdirSync(promptsDir, { recursive: true });
const outPath = join(promptsDir, "embedded.ts");
writeFileSync(outPath, out, "utf8");
console.log(`Wrote ${outPath} (${files.length} prompts)`);
