#!/usr/bin/env node
/**
 * Single source of truth: package.json "version".
 *
 * Syncs:
 *  - src/version.generated.ts  (compiled into binaries; intro card / --version)
 *  - manifests/homebrew/clai.rb
 *  - manifests/scoop/clai.json
 *  - package-lock.json root version fields
 *
 * Usage: node scripts/sync-version.mjs
 * Wired from build / compile / pretest so a hand-edit of package.json is enough.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const pkgPath = join(root, "package.json");
const MIRROR_BASE = (process.env.CLAI_MIRROR_BASE ?? "https://downloads.clai.aniketpandey.website").replace(/\/+$/, "");
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const version = pkg.version;
if (typeof version !== "string" || !/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(version)) {
  console.error(`sync-version: invalid package.json version: ${version}`);
  process.exit(1);
}

const changed = [];

function writeIfChanged(path, content) {
  const prev = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (prev === content) return;
  writeFileSync(path, content, "utf8");
  changed.push(path.replace(root + "/", ""));
}

// 1) Generated runtime constant (importable; survives bun --compile).
writeIfChanged(
  join(root, "src/version.generated.ts"),
  `/**
 * AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
 * Source of truth: package.json "version".
 */
export const VERSION = ${JSON.stringify(version)} as const;
export const VERSION_TAG = ${JSON.stringify(`v${version}`)} as const;
`,
);

// 2) Homebrew formula template — keep structure, only bump version line.
const rbPath = join(root, "manifests/homebrew/clai.rb");
if (existsSync(rbPath)) {
  let rb = readFileSync(rbPath, "utf8");
  const next = rb.replace(/version\s+"[^"]+"/, `version "${version}"`);
  if (next !== rb) {
    writeFileSync(rbPath, next, "utf8");
    changed.push("manifests/homebrew/clai.rb");
  }
}

// 3) Scoop template — version + concrete download URL for install tests.
const scoopPath = join(root, "manifests/scoop/clai.json");
if (existsSync(scoopPath)) {
  const scoop = JSON.parse(readFileSync(scoopPath, "utf8"));
  scoop.version = version;
  if (scoop.architecture?.["64bit"]?.url) {
    scoop.architecture["64bit"].url =
      `${MIRROR_BASE}/v${version}/clai-bun-windows-x64.exe#/clai.exe`;
  }
  const next = `${JSON.stringify(scoop, null, 2)}\n`;
  writeIfChanged(scoopPath, next);
}

// 4) package-lock root version (npm does this on `npm version`; keep CI green).
const lockPath = join(root, "package-lock.json");
if (existsSync(lockPath)) {
  const lock = JSON.parse(readFileSync(lockPath, "utf8"));
  let dirty = false;
  if (lock.version !== version) {
    lock.version = version;
    dirty = true;
  }
  if (lock.packages?.[""] && lock.packages[""].version !== version) {
    lock.packages[""].version = version;
    dirty = true;
  }
  if (dirty) {
    writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`, "utf8");
    changed.push("package-lock.json");
  }
}

if (changed.length === 0) {
  console.log(`sync-version: already at ${version}`);
} else {
  console.log(`sync-version: ${version} → ${changed.join(", ")}`);
}
