/**
 * AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
 * Source of truth: package.json "version".
 */
export const VERSION = "4.9.0" as const;
export const VERSION_TAG = "v4.9.0" as const;
