/**
 * AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
 * Source of truth: package.json "version".
 */
export const VERSION = "3.8.26" as const;
export const VERSION_TAG = "v3.8.26" as const;
